### ISSUE TITLE
Error when using Embedding

### ISSUE THREAD

**Issue by KazimirIskander** [BlenderNeko/ComfyUI_Cutoff#6]
When adding an Embed to the positive prompt, I get this error:

`Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "G:\ComfyUI\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "G:\ComfyUI\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "G:\ComfyUI\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  [Previous line repeated 6 more times]
  File "G:\ComfyUI\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "G:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Cutoff\cutoff.py", line 57, in add_clip_region
    prompt_tokens = np.array([[y[0] for y in x]for x in clip_regions["base_tokens"]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 77) + inhomogeneous part.`

Embedding used was the grin512 embed from the 512 Expressions TI pack (which I can't seem to find on civitAI anymore...)

**Comment by BlenderNeko** [comment]
this sounds like #2, can you pull changes and try again?

**Comment by KazimirIskander** [comment]
Yup, that fixed it. Thank you!
