### ISSUE TITLE
question: failed to run,AttributeError: 'CLIP' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by se7enth** [BlenderNeko/ComfyUI_Cutoff#8]
Did I need pip install clip again?
but I can run other node rightly.

Traceback (most recent call last):
  File "E:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "E:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  [Previous line repeated 7 more times]
  File "E:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "E:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Cutoff\cutoff.py", line 58, in init_prompt
    tokens = clip.tokenize(text, return_word_ids=True)
AttributeError: 'CLIP' object has no attribute 'tokenize'

**Comment by se7enth** [comment]
sure! I update all now it works!
